### ISSUE TITLE
Missing list styles

### ISSUE THREAD

**Issue by CedricVanhaverbeke** [samuelmeuli/draft-js-list-plugin#1]
Hi!

I'm using your plugin and it's working very nicely, except for importing the styles.
When I tab to add an indentation, the class name of the element is changing, but not rendering correctly for some reason. I had the manually add the CSS you are using in the demo to make it work:

As you can see, depth is 2 here:
![image](https://user-images.githubusercontent.com/10990125/75347095-573f4f80-58a0-11ea-8b3d-60ab3802df3e.png)

But there isn't any indentation. I had to add:
```css
.public-DraftStyleDefault-depth0.public-DraftStyleDefault-reset {
  counter-reset: ol0;
}

.public-DraftStyleDefault-depth1.public-DraftStyleDefault-reset {
  counter-reset: ol1;
}

.public-DraftStyleDefault-depth2.public-DraftStyleDefault-reset {
  counter-reset: ol2;
}

.public-DraftStyleDefault-depth3.public-DraftStyleDefault-reset {
  counter-reset: ol3;
}

.public-DraftStyleDefault-unorderedListItem.public-DraftStyleDefault-depth0 {
  list-style-type: disc;
}

.public-DraftStyleDefault-unorderedListItem.public-DraftStyleDefault-depth1 {
  list-style-type: circle;
}

.public-DraftStyleDefault-depth0.public-DraftStyleDefault-listLTR {
  margin-left: 1.5em;
}

.public-DraftStyleDefault-depth1.public-DraftStyleDefault-listLTR {
  margin-left: 3em;
}

.public-DraftStyleDefault-depth2.public-DraftStyleDefault-listLTR {
  margin-left: 4.5em;
}

.public-DraftStyleDefault-depth3.public-DraftStyleDefault-listLTR {
  margin-left: 6em;
}

.public-DraftStyleDefault-unorderedListItem {
  list-style-type: square;
  position: relative;
}

.public-DraftStyleDefault-listLTR {
  direction: ltr;
}
```

Am I missing something?
